### ISSUE TITLE
Duplicate script name

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/ewh-summer-2018#15]
https://github.com/redacademy/ewh-summer-2018/blob/95a1dde9f1ec7a00bcc2bc462fc1a7cb6319ae8b/themes/ewh/functions.php#L82

It looks like you have 2 scripts enqueued with the same reference name ```ewh-scripts```
This will cause an issue where only 1 of the script would load. I'm not sure if you need the second script as it only contains commented out code, maybe this is something you are working on? If you do need the 2nd script make sure to give it a unique name.

**Comment by benorgan** [comment]
And if you don't need the duplicate script then let's delete it from the repo rather than leaving commented out code.

**Comment by Juett** [comment]
changed all scripts to ewh, ewh1, and ewh2.
