### ISSUE TITLE
Birth control method boxes aren't filling the full width

### ISSUE THREAD

**Issue by benorgan** [redacademy/ewh-summer-2018#23]
This makes the page look off-centre

https://github.com/redacademy/ewh-summer-2018/blob/bc7b95b355b4ea5e0d253697063d47570883efe7/themes/ewh/sass/_birth-control.scss#L16

You could use justify-content to ensure the items fill the full width

**Comment by Safenorsound** [comment]
Thanks Ben, this has been updated.

**Comment by resonantdoghouse** [comment]
Looks good
